/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BitMaPNativeLib_BitMaP_DIBHeader */

#ifndef _Included_BitMaPNativeLib_BitMaP_DIBHeader
#define _Included_BitMaPNativeLib_BitMaP_DIBHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BitMaPNativeLib_BitMaP_DIBHeader
 * Method:    readFromFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BitMaPNativeLib_BitMaP_00024DIBHeader_readFromFile
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_BitMaPNativeLib_BitMaP_00024DIBHeader_saveInFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
