/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BitMaPNativeLib_BitMaP */

#ifndef _Included_BitMaPNativeLib_BitMaP
#define _Included_BitMaPNativeLib_BitMaP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BitMaPNativeLib_BitMaP
 * Method:    setContrast
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_BitMaPNativeLib_BitMaP_setContrast
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     BitMaPNativeLib_BitMaP
 * Method:    setBrightness
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_BitMaPNativeLib_BitMaP_setBrightness
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
