/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BitMaPNativeLib_BitMaP_DIBColorProfile */

#ifndef _Included_BitMaPNativeLib_BitMaP_DIBColorProfile
#define _Included_BitMaPNativeLib_BitMaP_DIBColorProfile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BitMaPNativeLib_BitMaP_DIBColorProfile
 * Method:    readFromFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BitMaPNativeLib_BitMaP_00024DIBColorProfile_readFromFile
  (JNIEnv *, jobject, jstring);

JNIEXPORT jint JNICALL Java_BitMaPNativeLib_BitMaP_00024DIBColorProfile_saveInFile
  (JNIEnv *, jobject, jstring);
#ifdef __cplusplus
}
#endif
#endif
