/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BitMaPNativeLib_BitMaP_FileHeader */

#ifndef _Included_BitMaPNativeLib_BitMaP_FileHeader
#define _Included_BitMaPNativeLib_BitMaP_FileHeader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BitMaPNativeLib_BitMaP_FileHeader
 * Method:    readFromFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BitMaPNativeLib_BitMaP_00024FileHeader_readFromFile
  (JNIEnv *, jobject, jstring);

/*
 * Class:     BitMaPNativeLib_BitMaP_FileHeader
 * Method:    saveInFile
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BitMaPNativeLib_BitMaP_00024FileHeader_saveInFile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
