/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BitMaPNativeLib_BitMaP_Data */

#ifndef _Included_BitMaPNativeLib_BitMaP_Data
#define _Included_BitMaPNativeLib_BitMaP_Data
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     BitMaPNativeLib_BitMaP_Data
 * Method:    readFromFile
 * Signature: (Ljava/lang/String;II)[[LBitMaPNativeLib/Pixel;
 */
JNIEXPORT jobjectArray JNICALL Java_BitMaPNativeLib_BitMaP_00024Data_readFromFile
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     BitMaPNativeLib_BitMaP_Data
 * Method:    saveInFile
 * Signature: (Ljava/lang/String;[[LBitMaPNativeLib/Pixel;II)V
 */
JNIEXPORT void JNICALL Java_BitMaPNativeLib_BitMaP_00024Data_saveInFile
  (JNIEnv *, jobject, jstring, jobjectArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
